---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

Group Members:
Andrew Shooman
Xiangyu Zeng
Thao Nguyen
Yunzhou Liu

```{r, warning=FALSE, message=FALSE}
library(readr)
library(mosaic)
houses = read_csv("AmesTrain2.csv")
```

```{r}
quantitative.house <- houses[c(2:4, 7:10, 17:19, 23:30, 32:33, 35:36, 39:42)]
head(quantitative.house)
```

## Part 1. Create an initial basic model

*build a model using Backward elimination, Forward selection, and Stepwise selection*

##### Build a model
```{r}
plot(quantitative.house$Price~., data=quantitative.house[c(2:26)])
```

```{r}
Full = lm(quantitative.house$Price~., data=quantitative.house[c(2:26)])
MSE=(summary(Full)$sigma)^2
backward.elimination = step(Full,scale=MSE, trace=FALSE)
summary(backward.elimination)
```

```{r}
none = lm(quantitative.house$Price~1, data=quantitative.house[2:26])
forward.selection = step(none, scope=list(upper=Full), scale=MSE, direction="forward", trace=FALSE)
summary(forward.selection)
```

```{r}

```


## Part 2. Residual Analysis for basic model


## Part 3. "Fancier model"


## Part 4. Residual Analysis for fancier model


## Part 5. Final Model
